### PR TITLE
Fix wrong Time.h include

### PR DESCRIPTION
**Pull request by MadddinTribleD**

### CODE REVIEW

**Comment by g3gg0** [comment]
Thanks. Its probably not even needed, as it compiled here.
All that .ino cruft is a bit intransparent. Should have used plain C and H files.

**Comment by MadddinTribleD** [comment]
Could not get it to compile on my side without changing the include.  
Not really sure either if its a system thing or just pio/arduiono magic

**Comment by g3gg0** [comment]
No i mean the header is probably not needed

**Comment by MadddinTribleD** [comment]
Ah well did not try without the file and the include.
IMO it is nicer to have the header files in place.

We could change the ino files to c files. Guess this would make it more understandable for people coming from a C background

**Pull request merged**
